name: Release Binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Static build for ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: linux/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary in container
        run: |
          docker build --platform ${{ matrix.platform }} --target builder -t builder .
          docker create --name temp builder
          docker cp temp:/app/target/release/vic ./vic-${{ matrix.arch }}
          docker rm temp

      - name: Tar with executable permissions
        run: |
          run: |
            chmod +x vic-${{ matrix.arch }}
            tar -czvf vic-${{ matrix.arch }}.tar.gz vic-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: vic-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
